### ISSUE TITLE
Улучшение Организации

### ISSUE THREAD

**Issue by hypnospinner** [krbroman/reddex_preyfish#6]
На данный момент репозиторий находится в плачевном состоянии с точки зрения организованности. Что плохо?

***

- [x] Поменять названия для issues. Предлагается переименовать issues #1 #2 #3 #4 #5, повсеместно использовать один и тот же язык (русский, но комментарии в коде - английский)

***

- [x] Пересмотреть **Labels**. Предлагается:
     - [x] Перевести все комментарии для Labels
     - [x] Labels более логично ассоциированные с теми или иными частями игры вывести в milesones (см.далее)
     - [x] Suggested Labels:
         - urgent (срочно)
         - important (важно)
         - enhancement/new feature (улучшение, новая фича, что-то про развитие вперед)
         - management (все что связано с управлением и организацией (планирование brain-storm)
         - bug

по ходу надобности Labels должны расширяться

***

- [x] Добавить Milestones

**Milestones** - те самый названия issues больше подходят milestone'ам - некоторым логическим временным этапам развития проектов, но и их самих не стоит так называть - максимально короткие, емкие и понятные названия для всего - наше все, но в шутку можно оставлять подобные комментарии. Я веду к тому, что стоит подумать об их использовании для того чтобы вот так себя подгонять (по сути делать дедлайны)

***

- [x] Добавить Projects (в нашем случае можно совсем их убрать(делается в Settings) или не убирать (см. далее))

**Projects** нужны на уровне архитектуры нашего приложения (т.е. когда мы прописываем взаимодействие между микросервисами, приложеними на мобилках, десктопе и вебе в рамках единой системы-программы.

**НО!** мы можем использовать их для разработки различных систем: inventory, combat (и т.д.)
Я рекомендую использовать их именно для этого.

***

- [x] Assign меня на какие-нибудь задачи

- [x] Переименовать проект (на GitHub "принято" называть проекты маленькими, используя тире вместо пробела (вкусовщина, но все же))

- [x] Добавить описание для проекта

- [ ] Добавить лицензию (необязательно)

- [ ] Добавить Readme

***

**_Помимо этого я предлагаю реализовать [ECS](https://unity3d.com/learn/tutorials/topics/scripting/introduction-ecs)_**

**_Почему?_**
1. Это новый подход, который в будущем станет основным (судя по всему)
2. Он гораздо эффективнее (7k против 150k объектов в сцене)

***
Помимо этого хочется чтобы issues стали более осмысленными и подробными (на уровне этого)

***
Прежде чем начинать добавлять что-то новое я предлагаю определится с фронтом работ, сделать фич-лист и внести данные в Wiki проекта - место где будут хранится любые важные с технической и не только точки зрения данные. Нужно помнить, что там должно быть только то, что доступно всем пользователям GitHub, поэтому не стоит размещать туда внутреннюю информацию

**Comment by hypnospinner** [comment]
Помимо этого хочется, чтобы issues были более осмысленными #4

**Comment by hypnospinner** [comment]
## О Project и Milestone

Те milestone, которые были созданы - не лучшее решение. 
Потому что milestone - крупный единичный шаг, а Projects - длительное множество шагов по развитию определенной части приложения.
Combat and AI - лучше разделить на 2 проекта (Combat это и про игрока тоже), вообще это идеальные названия для проектов, но не для milestone. Предлагается сделать Pre-development и Prototype milestones

**Comment by hypnospinner** [comment]
Так же было бы неплохо 

- [ ] Переназвать проект на 'preyfish'
